name: release

on:
  push:
    tags:
      - 'v*'
    branches:
      - master

jobs:
  build:
    name: build-windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          submodules: recursive
          
    - name: Figure out if we're running for a tag
      id: checktag
      run: |
        If($Env:GITHUB_REF -match "v([0-9]*)\.([0-9]*)\.([0-9]*)") {
            $IsRelease = "yes";
            $Version = $Matches[0];
            $VersionMinor = $Matches[1];
            $VersionMajor = $Matches[2];
            $VersionPatch = $Matches[3];
        } Else {
            $IsRelease = "no";
            $Version = $Env:GITHUB_SHA;
            $VersionMinor = 0;
            $VersionMajor = 0;
            $VersionPatch = 0;
        }
        Echo ("::set-output name=is_release::" + $IsRelease);
        Echo ("::set-output name=version::" + $Version);
        Echo ("::set-output name=version_major::" + $VersionMajor);
        Echo ("::set-output name=version_minor::" + $VersionMinor);
        Echo ("::set-output name=version_patch::" + $VersionPatch);

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Build Solution (x64)
      run: |
        cd ${{ github.workspace }}
        msbuild "-property:Configuration=Release;Platform=x64;CI_VERSION=${{ steps.checktag.outputs.version }}" SecureUxTheme.sln

    - name: Build Solution (ARM64)
      run: |
        cd ${{ github.workspace }}
        msbuild "-property:Configuration=Release;Platform=ARM64;CI_VERSION=${{ steps.checktag.outputs.version }}" SecureUxTheme.sln
        
      # Win32 built last
    - name: Build Solution (Win32)
      run: |
        cd ${{ github.workspace }}
        msbuild "-property:Configuration=Release;Platform=Win32;CI_VERSION=${{ steps.checktag.outputs.version }}" SecureUxTheme.sln

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          .\bin\Release\Win32\SecureUxTheme.dll
          .\bin\Release\x64\SecureUxTheme.dll
          .\bin\Release\ARM64\SecureUxTheme.dll
          .\bin\Release\Win32\ThemeTool.exe
          .\bin\Release\Win32\ThemeTool.pdb

    - name: Create release
      if: ${{ steps.checktag.outputs.is_release == 'yes' }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

    - name: Upload release asset
      if: ${{ steps.checktag.outputs.is_release == 'yes' }}
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: .\bin\Release\Win32\ThemeTool.exe
        asset_name: ThemeTool.exe
        asset_content_type: application/octet-stream
